apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:latest
          command: ["python", "-m", "api.service"]
          ports:
            - containerPort: 5001
            - containerPort: 5002
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: public-api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001  # Minikube exposes this

---
apiVersion: v1
kind: Service
metadata:
  name: admin-api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002  # Minikube exposes this
