apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor
  labels:
    app: conductor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conductor
  template:
    metadata:
      labels:
        app: conductor
    spec:
      containers:
        - name: conductor
          image: conductor:latest
          command: ["python", "-m" , "conductor.service"]
          imagePullPolicy: Never
